import RightBar from "./components/RightBar";
import LeftBar from "./components/LeftBar";
import "./globals.css";

export const metadata = {
  title: "Twitter Official ",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="bg-black text-white flex justify-around items-center divide-x h-screen w-full ">
        <LeftBar  />
        <div className=" w-4/6">{children}</div>
        <RightBar />
      </body>
    </html>
  );
}
